---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 19-1-7 下午3:03
--- 事件逻辑控制器

require('loader')
require('core.love_engine')
require('gdata.basedata')
require('utils.math_tool')

eventer = {}

function eventer.dojob(cur_scene,cur_mouse_x,cur_mouse_y,is_left_click,is_right_click)
    print(cur_scene,cur_mouse_x,cur_mouse_y,is_left_click,is_right_click)
    --位于title界面时的操作
    if math_tool.IsInTable(cur_scene,{basedata.SCENE_CODE.TITLE,basedata.SCENE_CODE.BF_EXIT,basedata.SCENE_CODE.BF_START,basedata.SCENE_CODE.BF_CONTINUE}) then
        if 350 < cur_mouse_x and cur_mouse_x < 625 and 413 < cur_mouse_y and cur_mouse_y < 465 then
            --选中开始游戏按钮时，切换状态
            loader.SCENE_STATUS.cur_scene=basedata.SCENE_CODE.BF_START
        elseif  410 < cur_mouse_x and cur_mouse_x < 545 and 540 < cur_mouse_y and cur_mouse_y < 587
        then
            --选中退出按钮时,
            loader.SCENE_STATUS.cur_scene=basedata.SCENE_CODE.BF_EXIT
        elseif  381 < cur_mouse_x and cur_mouse_x < 593 and 317 < cur_mouse_y and cur_mouse_y < 360
        then
            --选中继续按钮时,
            loader.SCENE_STATUS.cur_scene=basedata.SCENE_CODE.BF_CONTINUE
        end
    end
    if cur_scene ==basedata.SCENE_CODE.BF_START then
        if is_left_click==true then
            loader.SCENE_STATUS.cur_scene=basedata.SCENE_CODE.CREATE_USER
        end
    end
    if cur_scene ==basedata.SCENE_CODE.BF_EXIT then
        if is_left_click==true then
            --退出游戏
            love_engine.event.quit()
        end
    end
    if cur_scene ==basedata.SCENE_CODE.BF_START then
        if is_left_click==true then
            loader.SCENE_STATUS.cur_scene=basedata.SCENE_CODE.CREATE_USER
        end
    end
    if cur_scene ==basedata.SCENE_CODE.BF_CONTINUE then
        if is_left_click==true then
            --继续游戏,读取存档数据
        end
    end
end
