---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 19-1-7 下午3:10
--- 预加载游戏数据和资源，并提供给 eventer 和 painter使用

require('gdata.gamedata')
require('gdata.basedata')
require('core.love_engine')
loader = {}
--静态资源
loader.RESOURCE = {
    title_img = love_engine.graphics.newImage("resource/ui_items/title.jpg"),
    create_user_img = love_engine.graphics.newImage("resource/ui_items/create_user.jpg")
}
--初始场景
loader.SCENE_STATUS = {
    cur_scene = basedata.SCENE_CODE.TITLE
}



