---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 18-12-14 下午4:05
---
--预加载资源
require('core.love_engine')
require('loader')
require('painter')
require('eventer')
local utf8 = require("utf8")

function love.load()
    --游戏初始化，先校验存档文件是否存在
    last_saving_data = love_engine.filesystem.read('gamedata.txt',all)
    if last_saving_data == nil then
        --若无存档文件，则加载title_nosave页面,
        loader.SCENE_STATUS.cur_scene=basedata.SCENE_CODE.TITLE.name
        basedata.SCENE_CODE.TITLE.is_save=false
    else
        --若文档存在，则加载title界面。
        loader.SCENE_STATUS.cur_scene=basedata.SCENE_CODE.TITLE.name
        basedata.SCENE_CODE.TITLE.is_save=true
    end
    --捕捉鼠标相关信息
    mouse_left_clicked = false
    mouse_right_clicked = false
    is_left_click = false
    is_right_click = false

    -- enable key repeat so backspace can be held down to trigger love.keypressed multiple times.
    love.keyboard.setKeyRepeat(true)

end

function love.textinput(t)
    --仅当角色创建界面支持输入文本
    if loader.SCENE_STATUS.cur_scene == basedata.SCENE_CODE.CREATE_USER.name then
        if string.len(gamedata.Player.Name) <20 then
            --用户名称长度不超过20
            gamedata.Player.Name = gamedata.Player.Name .. t
        end
    end
end

function love.keypressed(key)
    --仅当角色创建界面支持输入文本
    if loader.SCENE_STATUS.cur_scene == basedata.SCENE_CODE.CREATE_USER.name then
        if key == "backspace" then
            -- get the byte offset to the last UTF-8 character in the string.
            local byteoffset = utf8.offset(gamedata.Player.Name, -1)

            if byteoffset then
                -- remove the last UTF-8 character.
                -- string.sub operates on bytes rather than UTF-8 characters, so we couldn't do string.sub(text, 1, -2).
                gamedata.Player.Name = string.sub(gamedata.Player.Name, 1, byteoffset - 1)
            end
        end
    end
end

--更新函数
function love.update()
    cur_mouse_x = love_engine.mouse.getX()
    cur_mouse_y = love_engine.mouse.getY()

    if love_engine.mouse.isDown("1") then
        mouse_left_clicked = true
    else
        if mouse_left_clicked ==true then
            mouse_left_clicked =false
            is_left_click = true
        end
    end

    if love_engine.mouse.isDown("2") then
        mouse_right_clicked = true
    else
        if mouse_right_clicked ==true then
            mouse_right_clicked =false
            is_right_click = true
        end
    end
    --执行更新事件
    eventer.dojob(loader.SCENE_STATUS.cur_scene,cur_mouse_x,cur_mouse_y,is_left_click,is_right_click)
    --重置参数
    is_left_click = false
    is_right_click = false

end


--画布
function love.draw()
    --根据场景持续作画
    painter.dojob(loader.SCENE_STATUS.cur_scene)
end


