---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 18-12-14 下午4:05
---
--预加载资源
require('gdata.gamedata')
require('core.love_engine')
require('utils.dt_converter')
function love.load()

    cur_mouse_x = 0
    cur_mouse_y = 0
    mouse_left_clicked = false
    mouse_right_clicked = false
    --读取存档文件
    last_saving_data = love_engine.filesystem.read('gamedata.txt',all)
    --赋值到游戏数据table
    gamedata = dt_converter.StrToTable(last_saving_data)

end


--更新函数
function love.update()

    --实时获取鼠标位置
    cur_mouse_x = love.mouse.getX()
    cur_mouse_y = love.mouse.getY()
    --print(cur_mouse_x,cur_mouse_y)
    --鼠标点击事件
    if love_engine.mouse.isDown("1") then
        mouse_left_clicked = true
    else
        if mouse_left_clicked ==true then
            mouse_left_clicked =false
            --单次鼠标左击事件写在此处
            gamedata.PlayerMoney = gamedata.PlayerMoney+1
            save_data = dt_converter.TableToStr(gamedata)
            fileData=love_engine.filesystem.newFileData(save_data,"gamedata.txt","base64")
            res =love_engine.filesystem.write("gamedata.txt", fileData)
            print(res)
        end
    end
    if love_engine.mouse.isDown("2") then
        mouse_right_clicked = true
    else
        if mouse_right_clicked ==true then
            mouse_right_clicked =false
            --单次鼠标右击事件写在此处
            gamedata.PlayerMoney = gamedata.PlayerMoney+1
        end
    end
end


--画布
function love.draw()
    love.graphics.print(gamedata.PlayerMoney)
end


