---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 19-1-7 下午3:03
--- 绘画逻辑控制器
require('loader')
require('core.love_engine')
require('gdata.basedata')
painter = {}
--cur_scene为当前场景/状态
function painter.dojob(cur_scene)
    --绘制游戏标题页面
    if cur_scene == basedata.SCENE_CODE.TITLE then
        love_engine.graphics.draw(loader.RESOURCE.title_img,0,0)
    end
    --绘制标题页面中开始按钮被选中的特效
    if cur_scene ==basedata.SCENE_CODE.BF_START then
        love_engine.graphics.draw(loader.RESOURCE.title_img, 0, 0)
        love_engine.graphics.rectangle("line", 348, 420, 275, 52)
    end
    --绘制标题页面中退出按钮被选中的特效
    if cur_scene ==basedata.SCENE_CODE.BF_EXIT then
        love_engine.graphics.draw(loader.RESOURCE.title_img, 0, 0)
        love_engine.graphics.rectangle("line", 415, 540, 135, 47)
    end
    --绘制标题页面中继续按钮被选中的特效
    if cur_scene ==basedata.SCENE_CODE.BF_EXIT then
        love_engine.graphics.draw(loader.RESOURCE.title_img, 0, 0)
        love_engine.graphics.rectangle("line", 381, 317, 593, 360)
    end
    --开始游戏进入角色创建页面
    if cur_scene==basedata.SCENE_CODE.CREATE_USER then
        love_engine.graphics.draw(loader.RESOURCE.create_user_img, 0, 0)
    end
end