---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 18-12-28 下午5:23
---
local json = require("framework.shared.json")
s = {}
s.a =1
s.b = 2
print(json.encode(s))