---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 18-12-28 上午10:29
--- love2d api 封装

--初始化对象
love_engine = {}
--[[
基础函数说明:
1 load 预先加载
2 update 更新函数
3 draw 画布
]]--
--图形处理工具
love_engine.graphics = love.graphics
--[[
load类 ：
newImage("test.jpg") 预先加载图片资源
draw类 ：
draw(object_name,x_point,y_point) 坐标画笔
rectangle("line", (var - 1) * 128, 636, 128, 128) 方格阵列
print(object_name) 文字画笔
]]--

--音频处理工具
love_engine.audio = love.audio
--[[
load类 ：
newSource("sounds/title.wav", "stream") 预先加载音频资源
draw类 ：
play(object_name) 播放音频资源
]]--

--文件系统管理工具
love_engine.filesystem = love.filesystem
--[[
setIdentity:设置游戏存档目录名
getIdentity:获取游戏存档目录名
newFileData("content","name.filetyle","base64 or other"): 创建一个新的文件对象

]]--

--鼠标交互
love_engine.mouse = love.mouse
--[[
update类:
getX() : 获取鼠标横轴坐标
getY() : 获取鼠标纵轴坐标
isDown() : 1为左键 2 右键
]]--

--系统实践
love_engine.event = love.event
--[[
update类:
quit() :退出游戏
]]--