---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 19-1-2 下午4:23
--- 游戏基础数据

basedata = {}
--游戏场景编号
basedata.SCENE_CODE = {
    --位于初始界面
    TITLE = {
      name = 'title',
      --是否含有存档
      is_save=false,
      --鼠标是否位于开始游戏按钮
      is_on_start =false,
      --鼠标是否位于离开游戏按钮
      is_on_exit =false,
      --鼠标是否位于继续游戏按钮（需有存档）
      is_on_continue=false,
      --存档是否损坏
      is_save_broken = false
    },

    --角色创建界面
    CREATE_USER = {
        name = 'create_user',
        --名字是否合法，长度大于0
        is_user_name_ok = false,
        --鼠标是否位于确认按钮上
        is_on_enter = false
    },
    --游戏主界面
    MAIN = {
        name = 'main',
        --鼠标是否位于退出按钮
        is_on_back = false,
        --鼠标是否位于保存按钮
        is_on_save = false,
        --保存成功
        is_saved = false
    }
}
