---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 19-1-2 下午4:23
--- 游戏基础数据

basedata = {}
--游戏场景编号
basedata.SCENE_CODE = {
    --位于初始界面
    TITLE = 'title',
    --选中开始游戏按钮(BF means before)
    BF_START = 'bf_start',
    --选中退出游戏按钮
    BF_EXIT = 'bf_exit',
    --选中继续游戏按钮
    BF_CONTINUE = 'bf_continue',

    --角色创建界面
    CREATE_USER = 'create_user',
    --游戏主界面
    MAIN = 'main'
}
