---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 18-12-14 下午4:48
--- 存档数据

gamedata = {}
--玩家信息
gamedata.Player = {
    --角色名
    Name = 'gewei',
    --金币
    Money = 0
}

